# ┌───────────────────────────────────────────────────────────────────┐
# │                                                                   │
# │                          IMPORTANT NOTE                           │
# │                                                                   │
# │   This file is synced with https://github.com/atomicgo/template   │
# │                                                                   │
# │        Please apply all changes to the template repository        │
# │                                                                   │
# └───────────────────────────────────────────────────────────────────┘

name: AtomicGo

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    if: "!contains(github.event.head_commit.message, 'autoupdate')" # Do not update docs for generated commits
    runs-on: ubuntu-latest
    steps:
      - name: Update Docs
        uses: atomicgo/ci@main
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TERM: xterm-256color
