on:
  schedule:
    - cron: "0 0 * * *"

name: AtomicGo (Daily)
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Update Docs
        uses: atomicgo/ci@main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TERM: xterm-256color
